config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end

  get "/backend", to:"backends#home"

  get 'static_text/index', to:'static_texts#index', as:'static_text_index'

  post "/graphql", to: "graphql#execute"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/products", to:"products#index"

  get "/products/add_image/:id", to:"products#add_image_form"

  patch "/products/add_image/:id", to:"products#add_image", as:"product"
  #post "/products/add_image/:id", to:"products#add_image", as:"product"

  get "/product/show/:id", to:"products#show", as:"show_product"

  get "/product/images/:id", to:"products#get_images", as:"get_product_images"




  get "/static_image", to:"static_images#index", as: "static_image_index"

  get "/static_image/new", to:"static_images#new"#, as: "static_image"

  post "/static_image/create", to:"static_images#create", as: "static_images"

  patch "/static_image/", to:"static_images#update"#, as: "static_images"

  get "/static_image/edit/:id", to:"static_images#edit", as: "static_images_edit"

  get "/static_image/show/:id", to:"static_images#show", as: "static_images_show"


  get '/static_text', to:'static_texts#show'
  get '/static_text/edit/:id', to:'static_texts#edit', as: 'edit_static_text'
  get '/static_text/new', to:'static_texts#edit', as: 'new_static_text'

  get '/new/image', to:'images#new', as: 'new_image'
  post '/create/image', to:'images#create', as: 'create_image'

  post '/user/avatar', to:'images#add_avatar', as:'add_avatar'

  post '/tour/add/day/image', to:'images#add_tour_day_image', as:'add_tour_day_image'
  post '/accommodation/add/room/image', to:'images#add_room_image', as:'add_accommodation_room_image'

end

app/models/static_image.rb
include ImageHelper
class StaticImage < ApplicationRecord
  belongs_to :shop
  include Rails.application.routes.url_helpers

  has_one_attached :image

  def images_urls
    images = []
    unless self.image.blank?
      new_type = ImageLoader.new(self.image)
      images.append(new_type)
    end
    return images
  end

end

app/controllers/static_images_controller.rb
class StaticImagesController < ApplicationController
  skip_before_action :verify_authenticity_token
  include Rails.application.routes.url_helpers

  def index
    @static_image = StaticImage.all
  end

  def show
    @static_image = StaticImage.find_by_id params[:id]
  end


  def new
    @static_image = StaticImage.new
  end

  def create
    shop_uid = params.require(:shop_uid)
    page_position = params.require(:static_image).permit(:page_position)["page_position"]
    image = params.require(:static_image).permit(images: [])["images"][0]

    shop = Shop.find_by_uid shop_uid

    if shop
      static_image = shop.static_images.new(page_position:page_position)
      static_image.image = image
      static_image.save
      shop.static_images.append(static_image)
    end

    redirect_to static_images_show_path static_image
  end

  def edit
    @static_image = StaticImage.find_by_id(params[:id])
  end

  def update

    id = params.require(:static_image).require(:id)

    @static_image = StaticImage.find_by_id(id)

    attributes = params.require(:static_image).permit(:page_position, :id, images: [])

    if attributes.has_key? 'images'
      image = attributes[:images][0]
      @static_image.image = image
    end

    page_position = attributes[:page_position]

    @static_image.page_position = page_position

    @static_image.save

    redirect_to static_images_show_path @static_image
  end


  def add_image_form
    @static_image = StaticImage.new
  end

  def add_image
    product = StaticImage.find_by_id params[:id]
    product.images.attach(params[:product][:images])
    redirect_to show_product_path product
  end

  def get_images

    @static_image = StaticImage.find_by_id params[:id]
    images = []
    @static_image.images.each do |img|
      images.append({'original': url_for(img),
                     '100x100': url_for(img.variant(resize: "100x100"))})
    end
    render json: {id:params[:id], images: images}

  end

end

app/views/static_images/add_image_form.html.erb
<%= form_with model: @static_image, local: true do |form| %>
    <%= form.text_field :page_position, placeholder: "page position" %><br>
    <%= form.file_field :images, multiple: true %><br>
    <%= form.submit %>
<% end %>

app/views/static_images/edit.html.erb
<%= form_with model: @static_image, local: true do |form| %>
    <%= form.text_field :page_position, placeholder: "page position", value: @static_image.page_position %><br>
    <%= form.file_field :images, multiple: true %><br>
    <%= form.text_field :id, hidden: true %>
    <%= form.submit %>
<% end %>

app/views/static_images/index.html.erb
<div class="row" id="static_images">
  <div class="col-lg-12">
    <h4>Static Texts</h4>
  </div>
  <div class="col-lg-12">
    <table style="width:100%" class="table-striped">
      <tr>
        <th>id</th>
        <th>pagePosition</th>
        <th>preview</th>
        <th></th>
      </tr>
      <tr v-for="static_image in static_images">
        <td>{{ static_image.id }}</td>
        <td>
          <div v-if="static_image.editing"><input v-model="static_image.pagePosition"></div>
          <div v-else="static_image.editing">{{ static_image.pagePosition }}</div>
        </td>
        <td>
          <div>
            <img v-if="static_image.images[0]" v-bind:src="static_image.images[0].v100100" alt="">
          </div>
        </td>
        <td>
          <!--<button v-if="static_image.editing" v-on:click="updateStaticText(static_text)">save</button>-->
          <button v-on:click="activateEdition(static_image)">Edit</button>
        </td>
      </tr>
      <!--<tr>-->
        <!--<td>New</td>-->
        <!--<td><div><input v-model="new_static_text.text" ></div></td>-->
        <!--<td><div><input v-model="new_static_text.language" ></div></td>-->
        <!--<td><div><input v-model="new_static_text.pagePosition" ></div></td>-->
        <!--<td><button v-on:click="saveStaticText(new_static_text)">New</button></td>-->
      <!--</tr>-->
    </table>
  </div>

  <div class="modal" tabindex="-1" role="dialog" id="updateImageModal">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Modal title</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Modal body text goes here.</p>

          <form enctype="multipart/form-data" action="/static_image" accept-charset="UTF-8" id="updateImageForm"
                method="post" @submit="closeModal">
            <input type="hidden" name="_method" value="patch">

            <input type="text" name="shop_uid">

            <input placeholder="page position" v-model="on_edit_static_image.pagePosition"
                   type="text" name="static_image[page_position]"
                   id="static_image_page_position"><br>

            <input multiple="multiple" type="file" name="static_image[images][]" id="static_image_images"><br>

            <input type="text" v-model="on_edit_static_image.id" name="static_image[id]" id="static_image_id" >

            <!--<input type="submit" name="commit" value="Update Static image" data-disable-with="Update Static image">-->
          </form>

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary" form="updateImageForm">Save changes</button>
        </div>
      </div>
    </div>
  </div>


    <div class="col-lg-12">
      <hr>
      <h4>New Static Image</h4>
      <form enctype="multipart/form-data" action="/static_image/create" accept-charset="UTF-8" method="post"><input type="hidden" name="authenticity_token" value="ByFbVxLuDY3Ik7S+gVMUFQfIO/CiNV92yIvIJewMqUZ2s5pcQ2TjwNCK21U8sq+zCVUMlQznN5WZd61uyzJlgA==">
        <label for="static_image_page_position">Page Position</label>
        <input placeholder="page position" type="text" name="static_image[page_position]" id="static_image_page_position"><br>

        <label for="static_image_images">Select Image</label>
        <input multiple="multiple" type="file" name="static_image[images][]" id="static_image_images"><br>
        <input type="submit" name="commit" value="Create Static image" data-disable-with="Create Static image">
      </form>
    </div>


</div>



<p id="notice"><%= notice %></p>

<%= javascript_include_tag "static_images_app.js" %>

app/views/static_images/new.html.erb
<%= form_with model: @static_image, local: true do |form| %>
    <%= form.text_field :page_position, placeholder: "page position" %><br>

    <%= form.file_field :images, multiple: true %><br>
    <%= form.submit %>
<% end %>

app/views/static_images/show.html.erb
<a href="<%= static_image_index_path %>">Static images</a>

<ul>
  <li><%= @static_image.id %></li>
  <li><%= @static_image.page_position %></li>
</ul>

<ul>
  <% @static_image.images_urls.each do |imgurl| %>
      <li>
      <h3>Tiny</h3>
        <img src="<%= imgurl.tiny %>" alt="">
      </li>
      <li>
        <h3>Card H</h3>
      <img src="<%= imgurl.card_h %>" alt="">
      </li>
      <li>
        <h3>Card V</h3>
      <img src="<%= imgurl.card_v %>" alt="">
      </li>
      <li>
        <h3>visor</h3>
      <img src="<%= imgurl.visor %>" alt="">
      </li>
      <li>
        <h3>visor_prev</h3>
      <img src="<%= imgurl.visor_prev %>" alt="">
      </li>
      <li>
        <h3>room_card</h3>
      <img src="<%= imgurl.room_card %>" alt="">
      </li>
      <li>
        <h3>m_card</h3>
      <img src="<%= imgurl.m_card %>" alt="">
      </li>
  <% end %>
</ul>