config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end

  get "/backend", to:"backends#home"

  get 'static_text/index', to:'static_texts#index', as:'static_text_index'

  post "/graphql", to: "graphql#execute"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/products", to:"products#index"

  get "/products/add_image/:id", to:"products#add_image_form"

  patch "/products/add_image/:id", to:"products#add_image", as:"product"
  #post "/products/add_image/:id", to:"products#add_image", as:"product"

  get "/product/show/:id", to:"products#show", as:"show_product"

  get "/product/images/:id", to:"products#get_images", as:"get_product_images"




  get "/static_image", to:"static_images#index", as: "static_image_index"

  get "/static_image/new", to:"static_images#new"#, as: "static_image"

  post "/static_image/create", to:"static_images#create", as: "static_images"

  patch "/static_image/", to:"static_images#update"#, as: "static_images"

  get "/static_image/edit/:id", to:"static_images#edit", as: "static_images_edit"

  get "/static_image/show/:id", to:"static_images#show", as: "static_images_show"


  get '/static_text', to:'static_texts#show'
  get '/static_text/edit/:id', to:'static_texts#edit', as: 'edit_static_text'
  get '/static_text/new', to:'static_texts#edit', as: 'new_static_text'

  get '/new/image', to:'images#new', as: 'new_image'
  post '/create/image', to:'images#create', as: 'create_image'

  post '/user/avatar', to:'images#add_avatar', as:'add_avatar'

  post '/tour/add/day/image', to:'images#add_tour_day_image', as:'add_tour_day_image'
  post '/accommodation/add/room/image', to:'images#add_room_image', as:'add_accommodation_room_image'

end

app/models/static_text.rb
class StaticText < ApplicationRecord
  belongs_to :shop

  def update_on_changes(**args)
    attrs = {}
    args.each do |key, val|
      attrs[key] = val if val
    end
    self.update_attributes(attrs)
  end
end

app/controllers/static_texts_controller.rb
class StaticTextsController < ApplicationController
  before_action :set_static_text, only: [:show, :edit, :update, :destroy]

  # GET /static_texts
  # GET /static_texts.json
  def index
    @static_texts = StaticText.all
  end

  # GET /static_texts/1
  # GET /static_texts/1.json
  def show
  end

  # GET /static_texts/new
  def new
    @static_text = StaticText.new
  end

  # GET /static_texts/1/edit
  def edit
  end

  # POST /static_texts
  # POST /static_texts.json
  def create
    @static_text = StaticText.new(static_text_params)

    respond_to do |format|
      if @static_text.save
        format.html { redirect_to @static_text, notice: 'Static text was successfully created.' }
        format.json { render :show, status: :created, location: @static_text }
      else
        format.html { render :new }
        format.json { render json: @static_text.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /static_texts/1
  # PATCH/PUT /static_texts/1.json
  def update
    respond_to do |format|
      if @static_text.update(static_text_params)
        format.html { redirect_to @static_text, notice: 'Static text was successfully updated.' }
        format.json { render :show, status: :ok, location: @static_text }
      else
        format.html { render :edit }
        format.json { render json: @static_text.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /static_texts/1
  # DELETE /static_texts/1.json
  def destroy
    @static_text.destroy
    respond_to do |format|
      format.html { redirect_to static_texts_url, notice: 'Static text was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_static_text
      @static_text = StaticText.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def static_text_params
      params.fetch(:static_text, {})
    end
end

app/helpers/static_texts_helper.rb
module StaticTextsHelper
end

app/views/static_texts/_form.html.erb
<%= form_with(model: static_text, local: true) do |form| %>
  <% if static_text.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(static_text.errors.count, "error") %> prohibited this static_text from being saved:</h2>

      <ul>
        <% static_text.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/static_texts/edit.html.erb
<h1>Editing Static Text</h1>

<%= render 'form', static_text: @static_text %>

<%= link_to 'Show', @static_text %> |
<%= link_to 'Back', static_texts_path %>

app/views/static_texts/index.html.erb
<div class="row" id="static_texts">
  <div class="col-lg-12">
    <h4>Static Texts</h4>
  </div>
  <div class="col-lg-12">

    <input v-model="shop_uid" >

    <table style="width:100%" class="table-striped">
      <tr>
        <th>id</th>
        <th>Text</th>
        <th>Language</th>
        <th>pagePosition</th>
        <th></th>
      </tr>
      <tr v-for="static_text in static_texts">
        <td>{{ static_text.id }}</td>
        <td>
          <div v-if="static_text.editing"><input v-model="static_text.text" ></div>
          <div v-else="static_text.editing">{{ static_text.text }}</div>
        </td>
        <td>
          <div v-if="static_text.editing"><input v-model="static_text.language"></div>
          <div v-else="static_text.editing">{{ static_text.language }}</div></td>
        <td>
          <div v-if="static_text.editing"><input v-model="static_text.pagePosition"></div>
          <div v-else="static_text.editing">{{ static_text.pagePosition }}</div>
        </td>
        <td>
          <button v-if="static_text.editing" v-on:click="updateStaticText(static_text)">save</button>
          <button v-else="static_text.editing" v-on:click="activateEdition(static_text)">Edit</button>
        </td>
      </tr>
      <tr>
        <td>New</td>
        <td><div><input v-model="new_static_text.text" ></div></td>
        <td><div><input v-model="new_static_text.language" ></div></td>
        <td><div><input v-model="new_static_text.pagePosition" ></div></td>
        <td><button v-on:click="saveStaticText(new_static_text)">New</button></td>
      </tr>
    </table>
  </div>
</div>



<p id="notice"><%= notice %></p>

<%= javascript_include_tag "static_texts_app.js" %>

app/views/static_texts/new.html.erb
<h1>New Static Text</h1>

<%= render 'form', static_text: @static_text %>

<%= link_to 'Back', static_texts_path %>

app/views/static_texts/show.html.erb
<div class="row" id="static_texts">
  <div class="col-lg-12">
    <h4>Static Texts</h4>
  </div>
  <div class="col-lg-12">
    <ol>
      <li v-for="static_text in static_texts">
        {{ static_text.text }}
      </li>
    </ol>
  </div>
</div>

<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_static_text_path(@static_text) %> |
<%= link_to 'Back', static_texts_path %>
<%= javascript_include_tag "static_texts_app.js" %>